name: Update README with jsdelivr content

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch content from jsdelivr
        run: |
          curl -s https://cdn.jsdelivr.net/gh/SomeTechyGuy/Cloudflare-WAF-Rule@main/AntiDDos.txt -o content.txt

      - name: Update README.md
        run: |
          sed -i '/<!-- BEGIN JSDELIVR CONTENT -->/,/<!-- END JSDELIVR CONTENT -->/d' README.md
          sed -i '1{/<!-- BEGIN JSDELIVR CONTENT -->/q}' README.md
          sed -i '1i<!-- BEGIN JSDELIVR CONTENT -->' README.md
          sed -i '1{/<!-- END JSDELIVR CONTENT -->/q}' README.md
          sed -i '1i\n```\n' README.md
          sed -i '1i'"$(cat content.txt)'"' README.md
          sed -i '1i\n```' README.md
          git add README.md
          git commit -m "Update README.md with jsdelivr content" --author "GitHub Actions" --date=$(date)
          git push --quiet https://github.com/${GITHUB_ACTOR}/${GITHUB_REPOSITORY}.git HEAD:main
