name: Update README with jsdelivr content

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch content from jsdelivr
        run: |
          curl -s https://cdn.jsdelivr.net/gh/SomeTechyGuy/Cloudflare-WAF-Rule@main/AntiDDos.txt -o content.txt

      - name: Update README.md
        run: |
          sed -i '/<!-- BEGIN JSDELIVR CONTENT -->/,/<!-- END JSDELIVR CONTENT -->/d' README.md
          sed -i '/<!-- BEGIN JSDELIVR CONTENT -->/r content.txt' README.md
          sed -i '/<!-- END JSDELIVR CONTENT -->/a\n```' README.md
